defaults:
  - _self_
  - override /algo_black: algo/ppo
  - override /algo_white: a2c # (baseline 폴더에 있다면 baseline/a2c 등)

# --- 평가 환경 설정 ---
board_size: 15
num_eval_envs: 100  # 100판 동시 진행
device: cuda        

# --- 모델 경로 ---
black_checkpoint: "results/models/BlackPlay_agent_PPO.pt"
white_checkpoint: "results/models/WhitePlay_agent_A2C.pt"